server:
  port: 8096
  
spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://192.168.208.1:12500/db_account
#      uri: mongodb://localhost:27017/db_account
  
eureka:
  client: 
    service-url:
#     defaultZone: http://localhost:8761/eureka
      defaultZone: http://192.168.208.1:8761/eureka
    registry-with-eureka: true
