server:
  port: 8090
  
spring:
  application:
    name: client-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_client
  
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-with-eureka: true
