server:
  port: 8094
  
spring:
  application:
    name: deposit-service    
  data:
    mongodb:
      uri: mongodb://localhost:12500/db_deposit
#      uri: mongodb://localhost:27017/db_deposit
      
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-with-eureka: true
    
resilience4j:
  circuitbreaker:
    instances:
      depositCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10