server:
  port: 8094
  
spring:
  application:
    name: deposit-service    
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_deposit
      
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-with-eureka: true