server:
  port: 8097

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: client-service
        uri: lb://client-service
        predicates:
        - Path=/m1/**
      - id: product-service
#        uri: lb://product-service
        uri: http://localhost:8091
        predicates:
        - Path=/m2/**
      - id: transaction-service
        uri: lb://transaction-service
        predicates:
        - Path=/m3/**
        filters:
        - RewritePath=/m3/(?<x>.*), /$\{x}
      - id: withdrawal-service
        uri: lb://withdrawal-service
        predicates:
        - Path=/m4/**
      - id: deposit-service
        uri: lb://deposit-service
        predicates:
        - Path=/m5/**
      - id: paymentproduct-service
        uri: lb://paymentproduct-service
        predicates:
        - Path=/m6/**