server:
  port: 8097

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: client-service
        uri: lb://client-service
        predicates:
        - Path=/clients/**
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/products/**
      - id: transaction-service
        uri: lb://transaction-service
        predicates:
        - Path=/transactions/**
      - id: withdrawal-service
        uri: lb://withdrawal-service
        predicates:
        - Path=/withdrawals/**
      - id: deposit-service
        uri: lb://deposit-service
        predicates:
        - Path=/deposits/**
      - id: paymentproduct-service
        uri: lb://paymentproduct-service
        predicates:
        - Path=/paymentproducts/**