server:
  port: 8097

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: client-service
        uri: http://localhost:8090
        predicates:
        - Path=/proyect/**
        filters:
        - RewritePath=/proyect/(?<x>.*), /$\{x}
        
      - id: product-service
        uri: http://localhost:8091
        predicates:
        - Path=/proyect/**
        filters:
        - RewritePath=/proyect/(?<x>.*), /$\{x}
        
      - id: transaction-service
        uri: http://localhost:8092
        predicates:
        - Path=/proyect/**
        filters:
        - RewritePath=/proyect/(?<x>.*), /$\{x}
        
      - id: withdrawal-service
        uri: http://localhost:8093
        predicates:
        - Path=/proyect/**
        filters:
        - RewritePath=/proyect/(?<x>.*), /$\{x}
        
      - id: deposit-service
        uri: http://localhost:8094
        predicates:
        - Path=/proyect/**
        filters:
        - RewritePath=/proyect/(?<x>.*), /$\{x}
        
      - id: paymentproduct-service
        uri: http://localhost:8095
        predicates:
        - Path=/proyect/**
        filters:
        - RewritePath=/proyect/(?<x>.*), /$\{x}