server:
  port: 8095
  
spring:
  application:
    name: paymentproduct-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_paymentproduct
      
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-with-eureka: true
      