server:
  port: 8091
  
spring:
  application:
    name: product-service
  data:
    mongodb:
#      uri: mongodb://192.168.208.1:12500/db_product
      uri: mongodb://localhost:27017/db_product

eureka:
  client: 
    service-url:
      defaultZone: http://192.168.208.1:8761/eureka
    registry-with-eureka: true

resilience4j:
  circuitbreaker:
    instances:
      productCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10