server:
  port: 8092

spring:
  application:
    name: transaction-service   
  data:
    mongodb:
      uri: mongodb://192.168.208.1:27017/db_transaction
#      uri: mongodb://localhost:27017/db_transaction

eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-with-eureka: true
    