server:
  port: 8093
  
spring:
  application:
    name: withdrawal-service   
  data:
    mongodb:
      uri: mongodb://localhost:12500/db_withdrawal
#      uri: mongodb://localhost:27017/db_withdrawal

eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-with-eureka: true